"""getting rid of charity reviews table

Revision ID: 45218bec838d
Revises: 64cd12295abe
Create Date: 2024-05-17 17:09:31.172658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45218bec838d'
down_revision = '64cd12295abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charity_reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_review', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('charity_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name='fk_charity_reviews_charity_id_charities'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_charity_reviews_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
