"""creating blogs table

Revision ID: 508edbfa09ac
Revises: d4458f91abd0
Create Date: 2024-05-20 16:09:03.589480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508edbfa09ac'
down_revision = 'd4458f91abd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(), nullable=False),
    sa.Column('blog_content', sa.String(), nullable=False),
    sa.Column('blog_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cover_img', sa.String(), nullable=False),
    sa.Column('blog_views', sa.Integer(), nullable=True),
    sa.Column('img1', sa.String(), nullable=True),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('img3', sa.String(), nullable=True),
    sa.Column('img4', sa.String(), nullable=True),
    sa.Column('img5', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_blog_posts_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
