"""remove table chairty_reviews

Revision ID: 64cd12295abe
Revises: dd8280319ea0
Create Date: 2024-05-17 13:57:28.970825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cd12295abe'
down_revision = 'dd8280319ea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chairty_reviews')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chairty_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('date_of_review', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('charity_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name='fk_chairty_reviews_charity_id_charities'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_chairty_reviews_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
