"""initial migration

Revision ID: b6d6a5dda600
Revises: 
Create Date: 2024-11-04 10:51:37.584065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6d6a5dda600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_name', sa.String(), nullable=False),
    sa.Column('charity_description', sa.String(), nullable=False),
    sa.Column('charity_location', sa.String(), nullable=False),
    sa.Column('charity_icon', sa.String(), nullable=True),
    sa.Column('charity_signup', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charity_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('user_icon', sa.String(), nullable=True),
    sa.Column('signup_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('blog_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blog_title', sa.String(), nullable=False),
    sa.Column('blog_content', sa.String(), nullable=False),
    sa.Column('blog_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('cover_img', sa.String(), nullable=False),
    sa.Column('blog_views', sa.Integer(), nullable=True),
    sa.Column('img1', sa.String(), nullable=True),
    sa.Column('img2', sa.String(), nullable=True),
    sa.Column('img3', sa.String(), nullable=True),
    sa.Column('img4', sa.String(), nullable=True),
    sa.Column('img5', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_blog_posts_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_blog_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charity_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_title', sa.String(), nullable=True),
    sa.Column('charity_review', sa.String(), nullable=True),
    sa.Column('review_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_charity_reviews_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_charity_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_donated', sa.Float(), nullable=True),
    sa.Column('date_of_donation', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_donations_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_donations_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('charity_reviews')
    op.drop_table('blog_posts')
    op.drop_table('users')
    op.drop_table('charities')
    # ### end Alembic commands ###
