"""adding charity review table

Revision ID: d4458f91abd0
Revises: 45218bec838d
Create Date: 2024-05-17 17:40:15.631137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4458f91abd0'
down_revision = '45218bec838d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charity_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charity_review', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('charity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name=op.f('fk_charity_reviews_charity_id_charities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_charity_reviews_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charity_reviews')
    # ### end Alembic commands ###
