"""adding user and donation tables

Revision ID: dd8280319ea0
Revises: 
Create Date: 2024-05-16 16:45:07.681776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8280319ea0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chairty_reviews')
    op.drop_table('charities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('charity_name', sa.VARCHAR(), nullable=False),
    sa.Column('charity_description', sa.VARCHAR(), nullable=False),
    sa.Column('charity_location', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charity_name')
    )
    op.create_table('chairty_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.Column('charity_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['charity_id'], ['charities.id'], name='fk_chairty_reviews_charity_id_charities'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
